name: 'SonarQube Workflow'
on: 'workflow_dispatch'
jobs:
  sonarqube:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v4'
      with:
        fetch-depth: 0
    - uses: 'actions/setup-java@v4'
      with:
        distribution: 'zulu'
        java-version: '17'
        java-package: 'jdk+fx'
        cache: 'gradle'
    - name: 'Pre-scan build'
      run: './gradlew build -x test'
    - name: 'Run SonarQube scan'
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        project_version: ${{ github.run_id }}
      run: >
        ./gradlew sonar
        -Dsonar.projectKey=FFSM-Pathfinder
        -Dsonar.projectName='FFSM Pathfinder'
        -Dsonar.projectVersion="gha.$project_version"
